### ISSUE TITLE
SteamBrew Theme Listing

### ISSUE THREAD

**Issue by shdwmtr** [EugeneXXXie/blueArchiveSteamSkin#1]
Hey, I'm the developer of Millennium, and one of my GitHub bots notified me of this repo. Would you be interested in your theme being added to https://steambrew.app/themes?

**Comment by EugeneXXXie** [comment]
Sure, I'd be happy to have my theme added to Steambrew!

**Comment by shdwmtr** [comment]
https://steambrew.app/theme?id=1wwKwvHrFuzMs7Kb1Uzu

Make sure to add proper `header_image` and `splash_image` in your skin.json

**Comment by EugeneXXXie** [comment]
I have fixed it now
